config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :products do
    resources :comments
  end
  resources :users
  resources :posts
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

   root 'static_pages#index'
   resources :orders, only: [:index, :show, :new, :create,]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Herokuredo</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
   <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" 
         data-target="#example-navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Digital Stencil</a>
      <%= form_tag("/products", method: "get") do %>
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
      <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
  <% else %>
  <li>
  <%= link_to('Login', new_user_session_path) %>
  </li>
  <% end %>
   </div>
   <div class="collapse navbar-collapse" id="example-navbar-collapse">
      <ul class="nav navbar-nav">
         <li class="active"><%= link_to "home", static_pages_index_path %> </li>
         <li><%= link_to "products", products_path %> </li>
         <li><%= link_to "upload", new_product_path %></li>
         <li><%= link_to "current gallery", root_path %> </li>
         <li><%= link_to "contact us", static_pages_contact_path %></li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               Categories coming soon!<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><a href="#">Male</a></li>
               <li><a href="#">Female</a></li>
               <li><a href="#"></a></li>
               <li class="divider"></li>
               <li><a href="#">lookbook</a></li>
               <li class="divider"></li>
               <li><a href="#">wtf</a></li>
            </ul>
         </li>
      </ul>
   </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



<%= yield %>

</body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<%= link_to "Stencil Now", root_path %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
   <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" 
         data-target="#example-navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Digital Stencil</a>
      <%= form_tag("/products", method: "get") do %>
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
   </div>
   <div class="collapse navbar-collapse" id="example-navbar-collapse">
      <ul class="nav navbar-nav">
         <li class="active"><%= link_to "home", static_pages_index_path %> </li>
         <li><%= link_to "products", products_path %> </li>
         <li><%= link_to "upload", new_product_path %></li>
         <li><%= link_to "current gallery", root_path %> </li>
         <li><%= link_to "contact us", static_pages_contact_path %></li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               Categories coming soon!<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><a href="#">Male</a></li>
               <li><a href="#">Female</a></li>
               <li><a href="#"></a></li>
               <li class="divider"></li>
               <li><a href="#">lookbook</a></li>
               <li class="divider"></li>
               <li><a href="#">wtf</a></li>
            </ul>
         </li>
      </ul>
   </div>
</nav>
<%= yield %>